#!/usr/bin/env node
/**
 * Regenerates `poseidon_params_golden.json` (#91).
 *
 * The golden file is the bridge between the JS-side derivation and the Rust
 * contracts: `contracts/membership-tree/src/poseidon_params.rs` vendors a copy
 * of the t=3 BN254 parameters (soroban-sdk keeps its own module private), and
 * its test suite hashes that vendored copy and compares the digest recorded
 * here. Neither side can drift without the other's test going red.
 *
 * Usage: node utils/gen_poseidon_golden.js   (or: npm run poseidon:golden)
 */

"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const audit = require("./poseidon_param_audit.js");

/** Widths that are vendored into Rust and therefore need a pinned digest. */
const VENDORED_WIDTHS = [3];

const toHex = (value) => value.toString(16).padStart(64, "0");

/**
 * Digest over the tables in exactly the order the Rust module lists them:
 * the MDS matrix row-major, then the round constants round-major. Order is part
 * of the commitment, so a transposed or reordered table is caught too.
 */
function digestTables(mds, roundConstants) {
  const hash = crypto.createHash("sha256");
  for (const row of mds) for (const cell of row) hash.update(Buffer.from(cell, "hex"));
  for (const constant of roundConstants) hash.update(Buffer.from(constant, "hex"));
  return hash.digest("hex");
}

function build() {
  const widths = VENDORED_WIDTHS.map((t) => {
    const roundsP = audit.CIRCOMLIB_ROUNDS_P[t - 2];
    const derived = audit.deriveParameters(t, audit.ROUNDS_F, roundsP);
    const roundConstants = derived.roundConstants.map(toHex);
    const mds = derived.mds.map((row) => row.map(toHex));
    return {
      t,
      rounds_f: audit.ROUNDS_F,
      rounds_p: roundsP,
      num_round_constants: roundConstants.length,
      round_constants: roundConstants,
      mds,
      digest_sha256: digestTables(mds, roundConstants),
    };
  });

  return {
    _comment:
      "Generated by circuits/utils/gen_poseidon_golden.js. Do not edit by hand; run `npm run poseidon:golden` in circuits/ to regenerate.",
    spec: "https://eprint.iacr.org/2019/458 (Grassi et al., USENIX Security 2021); reference generator generate_parameters_grain.sage",
    curve: "BN254",
    modulus: audit.P.toString(),
    field_bits: audit.FIELD_BITS,
    sbox_exponent: audit.ALPHA,
    security_bits: audit.SECURITY_BITS,
    widths,
  };
}

function main() {
  const target = path.join(__dirname, "poseidon_params_golden.json");
  const golden = build();
  fs.writeFileSync(target, `${JSON.stringify(golden, null, 2)}\n`);
  for (const w of golden.widths) {
    console.log(
      `t=${w.t}: ${w.num_round_constants} round constants, ${w.t}x${w.t} MDS, sha256=${w.digest_sha256}`,
    );
  }
  console.log(`written: ${target}`);
}

module.exports = { build, digestTables, VENDORED_WIDTHS };

if (require.main === module) main();
